# Generated by Django 5.2.6 on 2025-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbllp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpress',
            name='accent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
